# Maven

# Build your Java project and run tests with Apache Maven.
 
trigger:

- master
 
pool:

  vmImage: ubuntu-latest
 
steps:
 
- task: JavaToolInstaller@0

  displayName: Set up Java 17

  inputs:

    versionSpec: '17'

    jdkArchitectureOption: 'x64'

    jdkSourceOption: 'PreInstalled'
 
- bash: |

    google-chrome --version || true

    java -version

  displayName: Check Chrome and Java versions
 
- task: Maven@3

  displayName: Run Maven Tests

  inputs:

    mavenPomFile: 'pom.xml'

    mavenOptions: '-Xmx3072m'

    javaHomeOption: 'JDKVersion'

    jdkVersionOption: '17'

    jdkArchitectureOption: 'x64'

    publishJUnitResults: true

    testResultsFiles: '**/surefire-reports/TEST-*.xml'

    goals: 'clean test package'
 
- task: CopyFiles@2

  displayName: Copy WAR file

  inputs:

    Contents: '**/*.war'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'
 
- task: PublishBuildArtifacts@1

  displayName: Publish Artifact

  inputs:

    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

    ArtifactName: 'warfile'

    publishLocation: 'Container'
 